#!/usr/bin/env bash
# transfers a file from a client to a server with scp

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
# assigning parameters to variables

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# disabling strict host key checking

scp -o "StrictHostChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# checking if the file transfer was successful

if [$? -eq 0]
then
	echo "File Transferred Successfully"
else
	echo "File Transfer failed"
fi
