#!/usr/bin/env bash
# configuring web server 01 to have HTTP response header

# updating packages
sudo apt-get update
sudo apt-get install -y nginx

# creating ndex page
echo "Hello World!" | sudo tee /var/www/html/index.html

# performing a redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/audusunday permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# creating a custom error page

eco "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

#custom HTTP response header

sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# test for syntax errors
sudo nginx -t

#restart nginx
sudo service nginx restart
